# Generated by Django 4.1 on 2022-08-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True)),
                ('slug', models.CharField(max_length=150)),
            ],
        ),
    ]
